name: test-fast-ctc-decode

on: [push]

jobs:

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.68.2
          default: true
      - name: Rust unit tests
        run: cargo test
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Python unit tests
        run: |
          python3 -m venv venv3
          source venv3/bin/activate
          python3 -m pip install maturin numpy
          maturin -F python develop
          python3 tests/test_decode.py

  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.68.2
          default: true
      - name: Rust unit tests
        run: cargo test --features=resolver
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Python unit tests
        run: |
          python -m venv venv3
          venv3\Scripts\Activate.ps1
          python -m pip install maturin numpy
          maturin -F python develop
          python tests/test_decode.py
